import { projects } from "./projects";
import type { RagAdapter } from "./types";

function pause(ms: number, signal: AbortSignal) {
  return new Promise<void>((resolve, reject) => {
    signal.throwIfAborted();
    const abort = () => {
      clearTimeout(timer);
      reject(new DOMException("Stopped", "AbortError"));
    };
    const timer = setTimeout(() => {
      signal.removeEventListener("abort", abort);
      resolve();
    }, ms);
    signal.addEventListener("abort", abort, { once: true });
  });
}

export const demoAdapter: RagAdapter = {
  async *stream(request, signal) {
    signal.throwIfAborted();
    const project = projects.find((p) => p.id === request.projectId);
    if (!project) throw new Error("This project is no longer available.");
    const query =
      request.messages
        .filter((m) => m.role === "user")
        .at(-1)
        ?.content.toLowerCase() ?? "";
    yield { type: "status", text: "Opening sample sources…" };
    await pause(550, signal);
    const relevant = project.keywords?.some((k) => query.includes(k));
    const sources = relevant
      ? project.sources.filter((s) => request.documentIds.includes(s.id))
      : [];
    // Only use the canned answer when its full supporting sample set is available.
    const supported = relevant && sources.length === project.sources.length;
    yield { type: "sources", sources: supported ? sources : [] };
    yield { type: "status", text: "Writing sample response…" };
    const content = supported
      ? "**Sample response · not generated by an AI model**\n\n" +
        project.answer
      : "This demo does not have a supported answer to that question. Try one of the suggested questions to explore the sample sources. Connect your RAG backend to answer questions using your own documents.";
    const chunks = content.match(/\S+\s*/g) ?? [];
    for (const text of chunks) {
      await pause(24, signal);
      yield { type: "delta", text };
    }
    yield { type: "done" };
  },
};
